FROM alpine:3

LABEL author="Muhammad Yusuf"
LABEL company="Yusuf zaman now" website="https://linktr.ee/m16yusuf"

RUN mkdir hello
RUN echo "Hello world" > "hello/world.txt"

CMD cat "hello/world.txt"
